### ISSUE TITLE
It doesn't work with Mac OS X..

### ISSUE THREAD

**Issue by hayzamjs** [Ponai/Kriptie#1]
It is supposed to work with mac OS X isn't it? But it doesn't, mind fixing it for me ? I could really use some thing like this.

**Comment by Ponai** [comment]
Hi Hayzam!

Well I would if i could,but I don't have a Mac.Be aware that it's just a
personal project of mine and I put it on Github so others can use it/change
it etc.

Kind regards,
Ponai

Op zaterdag 28 februari 2015 heeft Hayzam Sherif <notifications@github.com>
het volgende geschreven:

**Comment by Fazelesswhite** [comment]
Let's have a small chat ? Are you available? ##crypto on freenode IRC?

**Comment by Fazelesswhite** [comment]
I could really use some help from you..

**Comment by Ponai** [comment]
Sorry,I don't use IRC. You may send me the specific details of the errors
you are encountering and maybe I know why it's not working.
It should work on a Mac indeed,as it's plain Java,but there might be some
things that did make it platform dependent and that I am not aware of.
Also make sure you installed the non-restricted policies for Java that
allow the keysize I am using.

Good luck!

Op zaterdag 28 februari 2015 heeft Hayzam Sherif <notifications@github.com>
het volgende geschreven:

**Comment by Fazelesswhite** [comment]
I wanna make something like this, or exactly like this for android and I am not a java developer so I don't know what to do. I guess this can also work with android with some tweaking?

**Comment by Ponai** [comment]
Ah nice!

Hmmm no that would be more work actually and you will need to know Java,so
I can encourage you to learn that. I was also originally planning on
creating this as an Android app,but I don't have the experience and no
phones to test it on.

If you want to create something like this for Android,I would start from
scratch,as the gui part will be completely different, but you could
probably use some minor parts from Kriptie.

Op zaterdag 28 februari 2015 heeft Hayzam Sherif <notifications@github.com>
het volgende geschreven:

**Comment by Fazelesswhite** [comment]
Oh okay, In that case, I'll just leave it at windows, I don't have the time to do all that. :)

**Comment by Ponai** [comment]
:-))

Op zaterdag 28 februari 2015 heeft Hayzam Sherif <notifications@github.com>
het volgende geschreven:
